# use_frameworks!
platform :ios, '8.0'
target 'KFXPhotoPickerManager_Example' do
  pod 'KFXPhotoPickerManager', :path => '../'

  target 'KFXPhotoPickerManager_Tests' do
    inherit! :search_paths

    
  end
end
